/* replace the top "Comments" link on works with "Hide Comments" */
$j("#show_comments_link_top").html("<a data-remote=\"true\" href=\"/comments/hide_comments?chapter_id=13325941\">Hide Comments <\/a>");
/* replace the top "Comments (#)" link with "Hide Comments (#)" */
$j("#show_comments_link").html("<a data-remote=\"true\" href=\"/comments/hide_comments?chapter_id=13325941\">Hide Comments (1)<\/a>");
/* load up the comments in their placeholder div */
$j("#comments_placeholder").html("");
$j("#comments_placeholder").append("<!-- START thread -->\n<ol class=\"thread\">\n\n      <!-- START of single comment -->\n<li class=\"odd comment group\" id=\"comment_50981527\" role=\"article\">\n      <h4 class=\"heading byline\">\n            Account Deleted\n            <span class=\'parent\'>\n              on <a href=\"/works/5782108/chapters/13325941\">Chapter 1<\/a>\n            <\/span>\n        <span class=\"posted datetime\">\n          <abbr class=\"day\" title=\"Friday\">Fri<\/abbr> <span class=\"date\">29<\/span>\n                                                 <abbr class=\"month\" title=\"January\">Jan<\/abbr> <span class=\"year\">2016<\/span>\n                                                 <span class=\"time\">02:52AM<\/span> <abbr class=\"timezone\" title=\"UTC\">UTC<\/abbr>\n        <\/span>\n      <\/h4>\n        <div class=\"icon\">\n            <span class=\"visitor icon\"><!-- visitor icon holder --><\/span>\n        <\/div>\n        <blockquote class=\"userstuff\">\n          <p>Just so you know, Firefox won\'t display Wingdings. You\'d be better off copy-and-pasting <a href=\"http://www.alanwood.net/demos/wingdings.html\" rel=\"nofollow\">the Unicode equivalent<\/a> for each character and then providing a translation in the notes.<\/p>\n        <\/blockquote>\n\n      <h5 class=\"landmark heading\">Comment Actions<\/h5>\n\n<ul class=\"actions\" id=\"navigation_for_comment_50981527\" >\n    <li id=\"add_comment_reply_link_50981527\"><a data-remote=\"true\" href=\"/comments/add_comment_reply?chapter_id=13325941&amp;id=50981527\">Reply<\/a><\/li>\n  <li><a href=\"/comments/50981527\">Thread<\/a><\/li>\n<\/ul>\n\n  <div id=\"delete_comment_placeholder_50981527\" style=\"display:none;\">\n  <\/div>\n\n    <div id=\"add_comment_reply_placeholder_50981527\" style=\"display: none;\">\n    <\/div>\n\n<\/li>\n<!-- END of single comment -->\n\n\n\n<!-- END thread -->\n");
$j("#comments_placeholder").append("</ol>");
$j("#comments_placeholder").append("");
/* roll down the comments */
$j("#comments_placeholder").slideDown();
